mercadopago/sdk-js

- README.md
- Added new Checkout Off Web section listing all exposed functions and their corresponding parameters
> [Feature] Add Checkout Off Web documentation

- README.md
Removed documentation that was not needed about internal configurations for tokenizer
> [Fix] Removed unnecessary params for tokenizer

- README.md
MercadoPago.js V2 uses our Device ID as a fraud prevention system to detect and analyze unusual customer behavior, prevent suspicious payout and improve payment approval.
The purpose of this pull request is to document a new feature toggle that enables/disables el device id fraud prevention system.
> Add advancedFraudPrevention documentation

- LICENSE
- README.md
This PR documents a `cardId` option for when creating a token with a saved card id
> Update documentation with cardId

- API/bricks/card-payment.md
- API/bricks/index.md
- API/card-form.md
- API/checkout-pro.md
- API/core-methods.md
- API/fields.md
- README.md
Added Bricks documentation and separated individual modules.
> Bricks Documentation

- API/bricks/payment.md
changed props from snake_case to camelCase
> fixed cardsIds and customerId

- README.md
- Add `onReady` missing function.
- Calling the Promise inside an async function.
> Fix broken code example

- API/card-form.md
Add description of Card Form's new callback `onBinChange`
> Add onBinChange callback

- API/bricks/card-payment.md
- API/bricks/index.md
- API/bricks/payment.md
- API/bricks/status-screen.md
This PR adds backURL support on Status Screen Brick
> Added BackURL support on Status Screen Brick

- API/bricks/card-payment.md
- API/bricks/payment.md
Added documentation for onBinChange functionality
> onBinChange documentation

- README.md
Update readme about install and usage section.
> [SDK] Update readme

- .npmignore
- package.json
- Add repository and issues section on package.json
- Fix pre-commit-config.yaml name on .npmignore
> [SDK] Add information on package.json

- API/bricks/card-payment.md
- API/bricks/payment.md
- API/bricks/status-screen.md
- API/bricks/wallet.md
Update and sort bricks `ErrorCause`s
> [Bricks] Update and sort on Error Causes

- API/fields.md
adding luhn validation on `validityChangeEvent`
> added luhn validation on validityChangeEvent'

- API/bricks/payment.md
`TicketData` was missing some props, with this PR we're adding them.
> Added missing props to TicketData

- package.json
> Update package.json's main field

- API/bricks/brand.md
Correct Brand Brick prop text.textColor to text.color
> Correct Brand Brick prop text.color (#1)

- .github/README.md
- docs/bricks/README.md
- docs/bricks/card-payment.md
- docs/bricks/legacy/wallet.md
- docs/bricks/payment.md
- docs/bricks/paymentReview.md
- docs/bricks/status-screen.md
Added documentation for Rebranding
> [2350] [Rebranding]

- docs/fields.md
> [a11y] Add ariaRequired docs

- docs/authenticator.md
Updating Fast Payments documentation, with new errors and new `confirmationLocation` property
> chore: update FastPayments documentation

- docs/core-methods.md
> added labels property
